---
- hosts: ka
  tasks:
  - name: copy ssh file
    copy:
      src: "{{ item }}"
      dest: /root/.ssh/
      force: yes
      mode: 0600
    loop:
      - authorized_keys
      - id_rsa
      - id_rsa.pub
      - host-ssh.py
  - name: chmod id_rsa.pub
    shell: "chmod 644 /root/.ssh/id_rsa.pub; mkdir -p /etc/docker"
  - name: ssh hosts
    shell: "python /root/.ssh/host-ssh.py"
  - name: delete files
    file:
      name: /root/.ssh/host-ssh.py
      state: absent
  - name: copy daemon file
    copy:
      src: daemon.json
      dest: /etc/docker/daemon.json
      force: yes
  - name: systemctl restart docker
    systemd:
      name: docker
      state: restarted