# 配置基础环境，安装yum源及基本软件
- hosts: ka
  remote_user: root
  vars:
    docker_mirrors: '["https://hhnrk38l.mirror.aliyuncs.com", "http://f1361db2.m.daocloud.io"]'
    docker_ip: '10.66.1.1/24'
    kubproxy_apiVersion: v1alpha1
    kubernetesVersion: v1.17.0
    controlPlaneEndpoint: "172.17.0.190:8443"
    etcd_endpoints: "- https://172.17.0.191:2379\n    - https://172.17.0.192:2379\n    - https://172.17.0.193:2379"
    podSubnet: 10.88.0.0/16
    kubadm_apiVersion: v1beta2
    kube_version: 1.16.3
    pause_version: 3.1
    etcd_version: 3.3.15-0
    coredns_version: 1.6.2
  roles:
    - sethost
    - docker-yum-soft
    - k8s-yum-soft

# 安装 cfssl工具
- hosts: etcd[0]
  remote_user: root
  vars:
    etcd_host_list: "127.0.0.1,172.17.0.191,172.17.0.192,172.17.0.193"
  roles:
    - cfssl

# 安装ETCD
- hosts: etcd
  remote_user: root
  vars:   
    etct_init_cluster_list: "GxEtcdTest01=https://172.17.0.191:2380,GxEtcdTest02=https://172.17.0.192:2380,GxEtcdTest03=https://172.17.0.193:2380"
  roles:
    - etcd

# 安装 haproxy 和 keepalived
- hosts: haproxy_keepalived
  remote_user: root
  vars:
    apiserver_ip: 172.17.0.190/24
    haproxy_list: "server  k8s-m1.skxj.uat 172.17.0.191:6443 check weight 1 maxconn 2000 check inter 2000 rise 2 fall 3\n    server  k8s-m2.skxj.uat 172.17.0.192:6443 check weight 1 maxconn 2000 check inter 2000 rise 2 fall 3\n    server  k8s-m3.skxj.uat 172.17.0.193:6443 check weight 1 maxconn 2000 check inter 2000 rise 2 fall 3"
  roles:
    - haproxy




  

