# 重命名计算机名称

- name: set-honstname
  raw: "echo {{ hostname|quote }} > /etc/hostname"
  when: hostname is defined and hostname != ""

- name: changed hostname
  shell: "hostname {{ hostname|quote }}"
  when: hostname is defined and hostname != ""

# 设置hosts文件

- name: set hosts
  copy:
    src: hosts.txt
    dest: /etc/hosts
    force: yes
    mode: 0644

# 关闭防火墙 selinux

- name: stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: disable selnux
  selinux:
      state: disabled # required. choices: enforcing;permissive;disabled. The SELinux mode


- name: swapoff -a
  shell: "swapoff -a && sysctl -w vm.swappiness=0 && sed -i 's/.*swap.*/#&/g' /etc/fstab"

# sysctl config

# - name: k8s-sysctl
#   sysctl:
#     name: "{{ item[0] }}"
#     value: "{{ item[1] }}"
#     state: present
#     reload: yes
#   loop:
#     - [net.ipv4.ip_forward, 1]
#     - [net.bridge.bridge-nf-call-ip6tables, 1]
#     - [net.bridge.bridge-nf-call-iptables, 1]

# sysctl config
- name: copy k8s-sysctl
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d
    mode: 0644
    force: yes

- name: modprobe
  modprobe:
    name: br_netfilter
    state: present

- name: excute k8sconf
  shell: "sysctl -p /etc/sysctl.d/k8s.conf"

# set ipvs
- name: copy ipvs.modules
  copy:
    src: ipvs.modules
    dest: /etc/sysconfig/modules/ipvs.modules
    mode: 0755

- name: set ipvs.modules
  shell: "bash /etc/sysconfig/modules/ipvs.modules && lsmod | grep -e ip_vs -e nf_conntrack_ipv4"

# time sync 

- name: install chrony
  yum:
    name: chrony
    state: present

- name: copy config file
  copy: 
    src: chrony.conf
    dest: /etc/chrony.conf
    backup: yes

- name: start chrony
  systemd:
      name: chronyd 
      enabled: true
      daemon_reload: yes
      state: restarted

